### ISSUE TITLE
Apply patches

### ISSUE THREAD

**Issue by SteveEbey73742** [GloriousEggroll/wine-staging#1]
I have the wine source from the git on WineHQ, and tried to apply the patches, but was not successful.  Could someone make a simple set of instructions to allow people to know where to extract the patches to, and how to apply them?

**Comment by GloriousEggroll** [comment]
standard wine staging instructions apply. it does not compile currently unless you disable some patch sets. I recommend waiting until all patch sets have been fixed because the list of patch sets to disable changes almost daily depending on what gets fixed or if there is a rebase.
